### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#589]
This issue is an epic and aggregates multiple subtasks which increase overall test coverage in BotKube.

## To do

- This issue is an epic and aggregates multiple subtasks which increase overall test coverage in BotKube.

## To do

- [x] https://github.com/infracloudio/botkube/issues/615
- [ ] Write unit tests across all packages
    - Go through each package, file by file, and write missing unit tests
    - Split it to multiple pull requests
    - Refactor the code to make unit testing possible
    - Write missing unit tests
    - Reduce cyclomatic complexity, especially in: `pkg/execute/executor.go`, `pkg/controller/controller.go`, and `pkg/notify/slack.go`

- [ ] Review related issues and close/resolve them:
    - #349

- Write missing E2E tests
    - #282
    - #307
    - #322
    - #426
    - Webhook
    - MS Teams

- Write missing unit tests
    - Refactor the code to make unit testing possible
    - Reduce cyclomatic complexity, especially in: `pkg/execute/executor.go`, `pkg/controller/controller.go`, and `pkg/notify/slack.go`
    - It would be good to reduce usage of `time.Sleep` (now there are 7 matches when searching for such usage)
- Consider adding additional integration tests (see related issues for inspiration)

- It would be good to reduce usage of `time.Sleep` (now there are 7 matches when searching for such usage)

## Reason

Currently, BotKube has a minimal testing - mostly by the integration tests which bases on fake K8s client and fake Slack bot.
To ensure all features work as expected, we should improve the test coverage.

**Comment by pkosiec** [comment]
Blocked by #220 as there wil be a bigger refactoring as a part of that task.

**Comment by pkosiec** [comment]
Moving it out from 0.13 after discussion with @mszostok - we will write missing unit tests gradually over time, same with refactoring of each package 👍
