### ISSUE TITLE
Make community-related improvements around BotKube repositories 

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#594]
To enhance community experience, it would be good to review and improve the following areas:

> ⚠️  **NOTE:** For all the following tasks - do them both in `botkube` and `botkube-docs` repo.

- [x] #630

- [x] Check all community health files
    - Review and improve existing ones if necessary
        - Consider improvements to PR and Issue templates 
    - Add missing ones: `GOVERNANCE.md`, `SECURITY.md`, possibly more (e.g. we could also describe git flow)
- [x] Use CODEOWNERS file
    - Enforce review from Code Owners

- [x] Cleanup repository structure if necessary (e.g. move images to the `assets` directory)
