### ISSUE TITLE
Support fine-grained configuration per channels for the same bot (e.g. Slack)

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#596]
## Overview

This issue is an epic and aggregates all the subtasks to finalize the complete feature.

## Reason

There is a demand in community—5 open issues with a lot of reactions—to make the configuration more flexible in regards which notification should be collected and where to send.

## Acceptance Criteria

- [x] #643
- [x] User is able to route notifications:
  - [x] to individual channels without needing to run multiple deployments.
  - [x] to a given channel based on the Kubernetes Namespace.
- [x] User is able to define `kubectl` permissions per channel—in particular, configuring what commands can be executed and in which Namespaces.
- [x] User-facing documentation is up-to-date.
- [x] Unit-test/e2e test coverage is added to ensure no regression in the future.

## To do

- [x] Prepare design draft / proposal - @mszostok, see:
    - https://github.com/infracloudio/botkube/pull/623,
    - https://github.com/infracloudio/botkube/pull/626
- [x] Gather community feedback about new design.
- [x] Prepare a list of subtasks. Split them into:
  - [x] required—those which need to be finished for MVP
  - [x] follow-up—those which can be addressed later
- [x] Start the asynchronous work to finish all required subtasks.

## Related issues
This issue aggregates the feature requests from:

- https://github.com/infracloudio/botkube/issues/250
- https://github.com/infracloudio/botkube/issues/486
- https://github.com/infracloudio/botkube/issues/444
- https://github.com/infracloudio/botkube/issues/508
- https://github.com/infracloudio/botkube/issues/542

All the tasks above will be eventually closed and the tracking of the feature will be done here.

**Comment by mszostok** [comment]
## Findings

The https://github.com/infracloudio/botkube/issues/250 is not strictly related to this issue, see: https://github.com/infracloudio/botkube/issues/250#issuecomment-1155030581

New related issues:
- https://github.com/infracloudio/botkube/issues/508
- https://github.com/infracloudio/botkube/issues/542

**Comment by pkosiec** [comment]
Closing as all subtasks have been resolved.
