### ISSUE TITLE
Onboarding Experience

### ISSUE THREAD

**Issue by brampling** [kubeshop/botkube#708]
## Overview

This epic aggregates the subtasks needed for the complete feature.

## Reason

User feedback we have received from BotKube users indicates that the BotKube installation process leads to a default configuration that is not tuned to their needs.

We want to improve the onboarding experience, in order to ensure that users can get value from BotKube as quickly and easily as possible.

- [x] https://github.com/kubeshop/botkube/issues/681
- [x] https://github.com/kubeshop/botkube/issues/683
- [x] https://github.com/kubeshop/botkube/issues/709
- [x] https://github.com/kubeshop/botkube/issues/703

**Comment by mszostok** [comment]
The last item (https://github.com/kubeshop/botkube/issues/703) on the list was recently merged, so we can close this issue.
