### ISSUE TITLE
Botkube Plugin System

### ISSUE THREAD

**Issue by huseyinbabal** [kubeshop/botkube#844]
This is the umbrella epic for [Event Extensibility](https://github.com/kubeshop/botkube/issues/650) and [Executor Extensibility ](https://github.com/kubeshop/botkube/issues/649)design epics. You can see the stories to implement a plugin system for Botkube to support both Source and Executor extensions.

### Design Documentation
https://github.com/kubeshop/botkube/blob/main/docs/proposal/2022-09-28-botkube-plugin-system.md

### Stories
 - [x] https://github.com/kubeshop/botkube/issues/838
 - [x] https://github.com/kubeshop/botkube/issues/843
 - [x] https://github.com/kubeshop/botkube/issues/839
 - [x] https://github.com/kubeshop/botkube/issues/925
 - [x] https://github.com/kubeshop/botkube/issues/901
 - [x] https://github.com/kubeshop/botkube/issues/899
 - [x] https://github.com/kubeshop/botkube/issues/870

 - [ ] https://github.com/kubeshop/botkube/issues/840
 - [x] https://github.com/kubeshop/botkube/issues/841

## Later
 - [ ] https://github.com/kubeshop/botkube/issues/842

 - [ ] https://github.com/kubeshop/botkube/issues/878
